# Generated by Django 2.1.7 on 2019-03-12 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190312_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='agency_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date_of_birth',
        ),
    ]
