# Generated by Django 2.1.7 on 2019-03-16 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0002_play_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viewing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='play',
            name='slug',
            field=models.SlugField(default='abc', unique=True),
        ),
        migrations.AddField(
            model_name='viewing',
            name='play_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plays.Play'),
        ),
    ]
