# Generated by Django 2.1.7 on 2019-03-20 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0007_seat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditorium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Auditorium1', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='seat',
            name='session',
        ),
    ]
