# Generated by Django 2.1.7 on 2019-03-20 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0008_auto_20190320_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewing',
            name='auditorium',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plays.Auditorium'),
        ),
    ]
