# Generated by Django 2.1.7 on 2019-03-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0011_auto_20190321_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewing',
            name='time',
            field=models.TimeField(),
        ),
    ]
