# Generated by Django 2.1.7 on 2019-04-01 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0013_auto_20190321_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='vacant',
            field=models.BooleanField(default=True),
        ),
    ]
