# Generated by Django 2.1.7 on 2019-04-01 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0014_auto_20190401_0431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='play',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='seat',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='view',
        ),
        migrations.AlterField(
            model_name='seat',
            name='number',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
