# Generated by Django 2.1.7 on 2019-03-24 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0013_auto_20190321_1234'),
        ('cart', '0003_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='plays',
        ),
        migrations.AddField(
            model_name='cart',
            name='seat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plays.Seat'),
        ),
    ]
