# Generated by Django 2.1.7 on 2019-03-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0013_auto_20190321_1234'),
        ('cart', '0004_auto_20190324_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='seat',
        ),
        migrations.AddField(
            model_name='cart',
            name='views',
            field=models.ManyToManyField(blank=True, to='plays.Viewing'),
        ),
    ]
