# Generated by Django 2.1.7 on 2019-03-25 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_cart_seat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='seat',
            new_name='seats',
        ),
    ]
