# Generated by Django 2.1.7 on 2019-03-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20190325_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('A', 'Standard Shipping'), ('B', 'First Class'), ('C', 'Pick up')], default=None, max_length=100, null=True)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
            ],
        ),
    ]
